### ISSUE TITLE
data example to start with?

### ISSUE THREAD

**Issue by mmandelli** [paulcbogdan/NiChord#1]
Hi there!your tool seems very nice! do you have a dataset as an example to start with? I am struggling a little to run the example

**Comment by paulcbogdan** [comment]
Have you tried downloading the repo and running `example\example.py`? It provides some edge data that is more elaborate than what the README.md provides. 

If you're having issues with calculating functional connectivity in general, the `nilearn` package provides some functions to easily download atlases and datasets.
